### ISSUE TITLE
broken markdown in README

### ISSUE THREAD

**Issue by matkoniecz** [tamasmeszaros/libnest2d#1]
see https://github.com/tamasmeszaros/libnest2d

> TOC {:toc}

at start look like something that was supposed to be autogenerated but it is not happening in Github dialect of markdown

**Comment by tamasmeszaros** [comment]
Hello,
Yes, it is not recognized by GitHub but on "GitHub pages" it is interpreted and the table of contents is displayed. As far as I know GitHub markdown doesn't support table of content generation so I was experimenting a little with workarounds.

**Comment by matkoniecz** [comment]
>  but on "GitHub pages" it is interpreted and the table of contents is displayed

That is because readme is interpreted as Markdown and GitHub Pages by default expect Jekyll ( https://github.com/jekyll/jekyll ) - what allows to use Jekyll Templates that are not in Markdown.

I think that readme should work without processing it (it requires generating readme, manual TOC composition or dropping TOC).
