### ISSUE TITLE
Running the example throws an error

### ISSUE THREAD

**Issue by Arun-A-P** [tamasmeszaros/libnest2d#13]
Was looking for 2D bin packers and this was some of the best code I found by far! Thank you for sharing this. I just had a problem with running the example program from ReadMe or the one in the examples folder. I get the following message : 

`libc++abi.dylib: terminating with uncaught exception of type libnest2d::GeometryException: Error while merging geometries!`

Do you have any idea what it could be? I'm working on macOS 10.14, and compiled a static library using CMake. I also have the libraries for all the dependencies including boost, clipper, NLopt in there.

**Comment by lolkusus** [comment]
I get the same error with example program.
Win 10, clipper, nlopt, boost.

**Comment by lolkusus** [comment]
I found solution.
In nfplacer.hpp
553:561 does not execute, therfore nfps is empty, so merging is not possible.

`#define LIBNEST2D_THREADING_std`
solves the problem.
