### ISSUE TITLE
GeometryException

### ISSUE THREAD

**Issue by rschurade** [tamasmeszaros/libnest2d#17]
Hi, I'm trying to use libnest2d in a VS2019 project. I tried all your install variants,  it compiles and links but when I run your simple example it always throws the GeometryException(GeomErr::MERGE); in geometries.hpp:328 

Any idea why valid would be false there and how I can debug what's going wrong?

**Comment by Mitsuriou** [comment]
Same error here. Built thanks to CMake with VS2017 compiler. It's compiling, linking and executing, both in a VS2017 and a VS2019 project.
I tried to change the shapes of the elements in the main, but changing the shapes makes me having 0 bin at the end. So I guess nothing is done with the shapes I defined.

**Comment by Mitsuriou** [comment]
Okay, I found a solution here : https://github.com/tamasmeszaros/libnest2d/issues/13

**Comment by rschurade** [comment]
Thanks that works.
