### ISSUE TITLE
Overlapping between irregular shapes shapes

### ISSUE THREAD

**Issue by TalhaSheikh-dev** [tamasmeszaros/libnest2d#26]
Hi first of all thanks for the code. 
I was using this and it works but it overlaps shapes. This happens when I use shapes with curves

I was hopping you can tell me where the problem is and can guide me how to solve it. or if can get a direction where the function is implemented to check the overlapping or anything else.

currently I am using its python version and if the issue is not solved I can move to cpp as well. So if you have solution in any implementation, you can give it
Would really appreciate your help
Thanks
![output](https://user-images.githubusercontent.com/72133879/102989697-db517a80-4537-11eb-8b59-28baf1f4a493.png)

**Comment by tamasmeszaros** [comment]
Sorry to let you down, but libnest2d doesn't support concave shapes on it's own. I can't provide any time estimate for that feature. You can try [SVGNest](https://github.com/Jack000/SVGnest), or [Plater](https://github.com/Rhoban/Plater) is also a great project capable of handling concave shapes.
