### ISSUE TITLE
Installation & Running Example

### ISSUE THREAD

**Issue by MCemGunes** [tamasmeszaros/libnest2d#55]
Hello, 

I have limited experience in C++ I might be missing some simple points in the installation but face some problems in the process.

Is it possible for anyone can demonstrate the step-by-step installation process? Because when I try to follow the instructions it does not run.

To have a clear platform I use Ubuntu 22.04 distribution in the docker environment. 

These are the commands that I use to create my environment:

```
FROM ubuntu:22.04
ENV PORT 80
EXPOSE $PORT

RUN apt-get update 
RUN apt install -y  wget curl ssh git

RUN apt-get install build-essential -y
RUN apt-get update && apt-get -y install cmake

WORKDIR /app
RUN git clone https://github.com/tamasmeszaros/libnest2d.git

WORKDIR /app/libnest2d/build
```

Then in `/app/libnest2d/build/` directory I run the following commands.

`cmake .. -DLIBNEST2D_HEADER_ONLY=OFF -DCMAKE_INSTALL_PREFIX=/usr  -DRP_ENABLE_DOWNLOADING=ON `

`cmake --build . --target install`

I do not get an error at this step. 

Then, I copied files in` /app/libnest2d/include/libnest2d/` directory to` /app/libnest2d/examples/`

In `/app/libnest2d/examples` directory I ran `g++ -I.  -std=c++17 main.cpp -o main` command to compile. But I got the error copied below. Probably I am failing to import some required libraries but I don't know how to fix this.

`In file included from main.cpp:6:
/usr/include/libnest2d/libnest2d.hpp:25:15: error: 'PointImpl' does not name a type; did you mean 'PointType'?
   25 | using Point = PointImpl;
      |               ^~~~~~~~~
      |               PointType
/usr/include/libnest2d/libnest2d.hpp:26:22: error: 'PointImpl' was not declared in this scope; did you mean 'PointType'?
   26 | using Coord = TCoord<PointImpl>;
      |                      ^~~~~~~~~
      |                      PointType
/usr/include/libnest2d/libnest2d.hpp:26:31: error: template argument 1 is invalid
   26 | using Coord = TCoord<PointImpl>;
      |                               ^
/usr/include/libnest2d/libnest2d.hpp:27:18: error: 'PointImpl' was not declared in this scope; did you mean 'PointType'?
   27 | using Box = _Box<PointImpl>;
      |                  ^~~~~~~~~
      |                  PointType
/usr/include/libnest2d/libnest2d.hpp:27:27: error: template argument 1 is invalid
   27 | using Box = _Box<PointImpl>;
      |                           ^
/usr/include/libnest2d/libnest2d.hpp:28:26: error: 'PointImpl' was not declared in this scope; did you mean 'PointType'?
   28 | using Segment = _Segment<PointImpl>;
      |                          ^~~~~~~~~
      |                          PointType
/usr/include/libnest2d/libnest2d.hpp:28:35: error: template argument 1 is invalid
   28 | using Segment = _Segment<PointImpl>;
      |                                   ^
/usr/include/libnest2d/libnest2d.hpp:29:24: error: 'PointImpl' was not declared in this scope; did you mean 'PointType'?
   29 | using Circle = _Circle<PointImpl>;
      |                        ^~~~~~~~~
      |                        PointType
/usr/include/libnest2d/libnest2d.hpp:29:33: error: template argument 1 is invalid
   29 | using Circle = _Circle<PointImpl>;
      |                                 ^
/usr/include/libnest2d/libnest2d.hpp:30:34: error: 'PolygonImpl' was not declared in this scope
   30 | using MultiPolygon = TMultiShape<PolygonImpl>;
      |                                  ^~~~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:30:45: error: template argument 1 is invalid
   30 | using MultiPolygon = TMultiShape<PolygonImpl>;
      |                                             ^
/usr/include/libnest2d/libnest2d.hpp:32:20: error: 'PolygonImpl' was not declared in this scope
   32 | using Item = _Item<PolygonImpl>;
      |                    ^~~~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:32:31: error: template argument 1 is invalid
   32 | using Item = _Item<PolygonImpl>;
      |                               ^
/usr/include/libnest2d/libnest2d.hpp:33:30: error: 'PolygonImpl' was not declared in this scope
   33 | using Rectangle = _Rectangle<PolygonImpl>;
      |                              ^~~~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:33:41: error: template argument 1 is invalid
   33 | using Rectangle = _Rectangle<PolygonImpl>;
      |                                         ^
/usr/include/libnest2d/libnest2d.hpp:34:30: error: 'PolygonImpl' was not declared in this scope
   34 | using PackGroup = _PackGroup<PolygonImpl>;
      |                              ^~~~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:34:41: error: template argument 1 is invalid
   34 | using PackGroup = _PackGroup<PolygonImpl>;
      |                                         ^
/usr/include/libnest2d/libnest2d.hpp:36:54: error: 'PolygonImpl' was not declared in this scope
   36 | using FillerSelection = selections::_FillerSelection<PolygonImpl>;
      |                                                      ^~~~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:36:65: error: template argument 1 is invalid
   36 | using FillerSelection = selections::_FillerSelection<PolygonImpl>;
      |                                                                 ^
/usr/include/libnest2d/libnest2d.hpp:37:58: error: 'PolygonImpl' was not declared in this scope
   37 | using FirstFitSelection = selections::_FirstFitSelection<PolygonImpl>;
      |                                                          ^~~~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:37:69: error: template argument 1 is invalid
   37 | using FirstFitSelection = selections::_FirstFitSelection<PolygonImpl>;
      |                                                                     ^
/usr/include/libnest2d/libnest2d.hpp:38:49: error: 'PolygonImpl' was not declared in this scope
   38 | using DJDHeuristic  = selections::_DJDHeuristic<PolygonImpl>;
      |                                                 ^~~~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:38:60: error: template argument 1 is invalid
   38 | using DJDHeuristic  = selections::_DJDHeuristic<PolygonImpl>;
      |                                                            ^
/usr/include/libnest2d/libnest2d.hpp:41:46: error: 'PolygonImpl' was not declared in this scope
   41 | using _NfpPlacer = placers::_NofitPolyPlacer<PolygonImpl, Bin>;
      |                                              ^~~~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:41:62: error: template argument 1 is invalid
   41 | using _NfpPlacer = placers::_NofitPolyPlacer<PolygonImpl, Bin>;
      |                                                              ^
/usr/include/libnest2d/libnest2d.hpp:44:19: error: '_NfpPlacer' does not name a type
   44 | using NfpPlacer = _NfpPlacer<Box>;
      |                   ^~~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:47:53: error: 'PolygonImpl' was not declared in this scope
   47 | using BottomLeftPlacer = placers::_BottomLeftPlacer<PolygonImpl>;
      |                                                     ^~~~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:47:64: error: template argument 1 is invalid
   47 | using BottomLeftPlacer = placers::_BottomLeftPlacer<PolygonImpl>;
      |                                                                ^
/usr/include/libnest2d/libnest2d.hpp:60:25: error: 'NfpPlacer' does not name a type
   60 | template<class Placer = NfpPlacer, class Selector = FirstFitSelection>
      |                         ^~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:60:53: error: 'FirstFitSelection' does not name a type
   60 | template<class Placer = NfpPlacer, class Selector = FirstFitSelection>
      |                                                     ^~~~~~~~~~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:87:25: error: 'NfpPlacer' does not name a type
   87 | template<class Placer = NfpPlacer,
      |                         ^~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:88:27: error: 'FirstFitSelection' does not name a type
   88 |          class Selector = FirstFitSelection,
      |                           ^~~~~~~~~~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:89:39: error: 'Item' was not declared in this scope
   89 |          class Iterator = std::vector<Item>::iterator>
      |                                       ^~~~
/usr/include/libnest2d/libnest2d.hpp:89:43: error: template argument 1 is invalid
   89 |          class Iterator = std::vector<Item>::iterator>
      |                                           ^
/usr/include/libnest2d/libnest2d.hpp:89:43: error: template argument 2 is invalid
/usr/include/libnest2d/libnest2d.hpp:89:46: error: expected '>' before 'iterator'
   89 |          class Iterator = std::vector<Item>::iterator>
      |                                              ^~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:92:18: error: 'Coord' has not been declared
   92 |                  Coord dist = 0,
      |                  ^~~~~
/usr/include/libnest2d/libnest2d.hpp:121:25: error: 'NfpPlacer' does not name a type
  121 | template<class Placer = NfpPlacer,
      |                         ^~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:122:27: error: 'FirstFitSelection' does not name a type
  122 |          class Selector = FirstFitSelection,
      |                           ^~~~~~~~~~~~~~~~~
/usr/include/libnest2d/libnest2d.hpp:123:40: error: 'Item' was not declared in this scope
  123 |          class Container = std::vector<Item>>
      |                                        ^~~~
/usr/include/libnest2d/libnest2d.hpp:123:40: error: template argument 1 is invalid
/usr/include/libnest2d/libnest2d.hpp:123:40: error: template argument 2 is invalid
/usr/include/libnest2d/libnest2d.hpp:126:18: error: 'Coord' has not been declared
  126 |                  Coord dist = 0,
      |                  ^~~~~
/usr/include/libnest2d/libnest2d.hpp:133:77: error: 'PointImpl' was not declared in this scope; did you mean 'PointType'?
  133 | template<class T = double> enable_if_t<std::is_arithmetic<T>::value, TCoord<PointImpl>> mm(T val = T(1))
      |                                                                             ^~~~~~~~~
      |                                                                             PointType
/usr/include/libnest2d/libnest2d.hpp:133:77: error: template argument 1 is invalid
/usr/include/libnest2d/libnest2d.hpp:133:86: error: template argument 2 is invalid
  133 | template<class T = double> enable_if_t<std::is_arithmetic<T>::value, TCoord<PointImpl>> mm(T val = T(1))
      |                                                                                      ^~
/usr/include/libnest2d/libnest2d.hpp: In function 'int libnest2d::mm(T)':
/usr/include/libnest2d/libnest2d.hpp:135:19: error: 'PointImpl' was not declared in this scope; did you mean 'PointType'?
  135 |     return TCoord<PointImpl>(val * CoordType<PointImpl>::MM_IN_COORDS);
      |                   ^~~~~~~~~
      |                   PointType
/usr/include/libnest2d/libnest2d.hpp:135:28: error: template argument 1 is invalid
  135 |     return TCoord<PointImpl>(val * CoordType<PointImpl>::MM_IN_COORDS);
      |                            ^
In file included from main.cpp:8:
../tools/printer_parts.hpp: At global scope:
../tools/printer_parts.hpp:7:41: error: 'PathImpl' is not a member of 'libnest2d'
    7 | using TestData = std::vector<libnest2d::PathImpl>;
      |                                         ^~~~~~~~
../tools/printer_parts.hpp:7:49: error: template argument 1 is invalid
    7 | using TestData = std::vector<libnest2d::PathImpl>;
      |                                                 ^
../tools/printer_parts.hpp:7:49: error: template argument 2 is invalid
../tools/printer_parts.hpp:8:43: error: 'PolygonImpl' is not a member of 'libnest2d'
    8 | using TestDataEx = std::vector<libnest2d::PolygonImpl>;
      |                                           ^~~~~~~~~~~
../tools/printer_parts.hpp:8:54: error: template argument 1 is invalid
    8 | using TestDataEx = std::vector<libnest2d::PolygonImpl>;
      |                                                      ^
../tools/printer_parts.hpp:8:54: error: template argument 2 is invalid
../tools/printer_parts.hpp:10:14: error: 'TestData' does not name a type
   10 | extern const TestData PRINTER_PART_POLYGONS;
      |              ^~~~~~~~
../tools/printer_parts.hpp:11:14: error: 'TestData' does not name a type
   11 | extern const TestData STEGOSAUR_POLYGONS;
      |              ^~~~~~~~
../tools/printer_parts.hpp:12:14: error: 'TestDataEx' does not name a type
   12 | extern const TestDataEx PRINTER_PART_POLYGONS_EX;
      |              ^~~~~~~~~~
main.cpp:13:26: error: 'Item' was not declared in this scope; did you mean 'tm'?
   13 | static const std::vector<Item>& _parts(std::vector<Item>& ret, const TestData& data)
      |                          ^~~~
      |                          tm
main.cpp:13:30: error: template argument 1 is invalid
   13 | static const std::vector<Item>& _parts(std::vector<Item>& ret, const TestData& data)
      |                              ^
main.cpp:13:30: error: template argument 2 is invalid
main.cpp:13:52: error: 'Item' was not declared in this scope; did you mean 'tm'?
   13 | static const std::vector<Item>& _parts(std::vector<Item>& ret, const TestData& data)
      |                                                    ^~~~
      |                                                    tm
main.cpp:13:56: error: template argument 1 is invalid
   13 | static const std::vector<Item>& _parts(std::vector<Item>& ret, const TestData& data)
      |                                                        ^
main.cpp:13:56: error: template argument 2 is invalid
main.cpp:13:70: error: 'TestData' does not name a type
   13 | static const std::vector<Item>& _parts(std::vector<Item>& ret, const TestData& data)
      |                                                                      ^~~~~~~~
main.cpp: In function 'const int& _parts(int&, const int&)':
main.cpp:15:12: error: request for member 'empty' in 'ret', which is of non-class type 'int'
   15 |     if(ret.empty()) {
      |            ^~~~~
main.cpp:16:13: error: request for member 'reserve' in 'ret', which is of non-class type 'int'
   16 |         ret.reserve(data.size());
      |             ^~~~~~~
main.cpp:16:26: error: request for member 'size' in 'data', which is of non-class type 'const int'
   16 |         ret.reserve(data.size());
      |                          ^~~~
main.cpp:17:25: error: 'begin' was not declared in this scope
   17 |         for(auto& inp : data)
      |                         ^~~~
main.cpp:17:25: note: suggested alternatives:
In file included from /usr/include/c++/11/string:54,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from main.cpp:1:
/usr/include/c++/11/bits/range_access.h:108:37: note:   'std::begin'
  108 |   template<typename _Tp> const _Tp* begin(const valarray<_Tp>&) noexcept;
      |                                     ^~~~~
In file included from /usr/include/libnest2d/nester.hpp:11,
                 from /usr/include/libnest2d/libnest2d.hpp:16,
                 from main.cpp:6:
/usr/include/libnest2d/geometry_traits.hpp:791:13: note:   'libnest2d::shapelike::begin'
  791 | inline auto begin(S& sh) -> decltype(begin(sh, Tag<S>()))
      |             ^~~~~
main.cpp:17:25: error: 'end' was not declared in this scope
   17 |         for(auto& inp : data)
      |                         ^~~~
main.cpp:17:25: note: suggested alternatives:
In file included from /usr/include/c++/11/string:54,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from main.cpp:1:
/usr/include/c++/11/bits/range_access.h:110:37: note:   'std::end'
  110 |   template<typename _Tp> const _Tp* end(const valarray<_Tp>&) noexcept;
      |                                     ^~~
In file included from /usr/include/libnest2d/nester.hpp:11,
                 from /usr/include/libnest2d/libnest2d.hpp:16,
                 from main.cpp:6:
/usr/include/libnest2d/geometry_traits.hpp:817:13: note:   'libnest2d::shapelike::end'
  817 | inline auto end(S& sh) -> decltype(begin(sh, Tag<S>()))
      |             ^~~
main.cpp:18:17: error: request for member 'emplace_back' in 'ret', which is of non-class type 'int'
   18 |             ret.emplace_back(inp);
      |                 ^~~~~~~~~~~~
main.cpp: At global scope:
main.cpp:24:26: error: 'Item' was not declared in this scope; did you mean 'tm'?
   24 | static const std::vector<Item>& prusaParts() {
      |                          ^~~~
      |                          tm
main.cpp:24:30: error: template argument 1 is invalid
   24 | static const std::vector<Item>& prusaParts() {
      |                              ^
main.cpp:24:30: error: template argument 2 is invalid
main.cpp: In function 'const int& prusaParts()':
main.cpp:25:24: error: 'Item' was not declared in this scope; did you mean 'tm'?
   25 |     static std::vector<Item> ret;
      |                        ^~~~
      |                        tm
main.cpp:25:28: error: template argument 1 is invalid
   25 |     static std::vector<Item> ret;
      |                            ^
main.cpp:25:28: error: template argument 2 is invalid
main.cpp:26:24: error: 'PRINTER_PART_POLYGONS' was not declared in this scope
   26 |     return _parts(ret, PRINTER_PART_POLYGONS);
      |                        ^~~~~~~~~~~~~~~~~~~~~
main.cpp: In function 'int main()':
main.cpp:31:17: error: 'Item' was not declared in this scope; did you mean 'tm'?
   31 |     std::vector<Item> input = prusaParts();
      |                 ^~~~
      |                 tm
main.cpp:31:21: error: template argument 1 is invalid
   31 |     std::vector<Item> input = prusaParts();
      |                     ^
main.cpp:31:21: error: template argument 2 is invalid
main.cpp:33:42: error: 'Box' was not declared in this scope
   33 |     size_t bins = libnest2d::nest(input, Box(mm(250), mm(210)), 0, {},
      |                                          ^~~
main.cpp:38:5: error: 'PackGroup' was not declared in this scope
   38 |     PackGroup pgrp(bins);
      |     ^~~~~~~~~
main.cpp:40:20: error: found ':' in nested-name-specifier, expected '::'
   40 |     for (Item &itm : input) {
      |                    ^
      |                    ::
main.cpp:40:16: error: 'itm' has not been declared
   40 |     for (Item &itm : input) {
      |                ^~~
main.cpp:44:5: error: expected primary-expression before 'using'
   44 |     using SVGWriter = libnest2d::svg::SVGWriter<PolygonImpl>;
      |     ^~~~~
main.cpp:42:6: error: expected ';' before 'using'
   42 |     }
      |      ^
      |      ;
   43 | 
   44 |     using SVGWriter = libnest2d::svg::SVGWriter<PolygonImpl>;
      |     ~~~~~
main.cpp:44:5: error: expected primary-expression before 'using'
   44 |     using SVGWriter = libnest2d::svg::SVGWriter<PolygonImpl>;
      |     ^~~~~
main.cpp:42:6: error: expected ')' before 'using'
   42 |     }
      |      ^
      |      )
   43 | 
   44 |     using SVGWriter = libnest2d::svg::SVGWriter<PolygonImpl>;
      |     ~~~~~
main.cpp:40:9: note: to match this '('
   40 |     for (Item &itm : input) {
      |         ^
main.cpp:44:49: error: 'PolygonImpl' was not declared in this scope
   44 |     using SVGWriter = libnest2d::svg::SVGWriter<PolygonImpl>;
      |                                                 ^~~~~~~~~~~
main.cpp:44:60: error: template argument 1 is invalid
   44 |     using SVGWriter = libnest2d::svg::SVGWriter<PolygonImpl>;
      |                                                            ^
main.cpp:45:5: error: 'SVGWriter' has not been declared
   45 |     SVGWriter::Config conf;
      |     ^~~~~~~~~
main.cpp:46:5: error: 'conf' was not declared in this scope; did you mean 'cosf'?
   46 |     conf.mm_in_coord_units = mm();
      |     ^~~~
      |     cosf
main.cpp:47:5: error: 'SVGWriter' was not declared in this scope; did you mean 'libnest2d::svg::SVGWriter'?
   47 |     SVGWriter svgw(conf);
      |     ^~~~~~~~~
      |     libnest2d::svg::SVGWriter
In file included from main.cpp:9:
../tools/svgtools.hpp:13:7: note: 'libnest2d::svg::SVGWriter' declared here
   13 | class SVGWriter {
      |       ^~~~~~~~~
main.cpp:48:5: error: 'svgw' was not declared in this scope
   48 |     svgw.setSize(Box(mm(250), mm(210)));
      |     ^~~~
main.cpp:49:25: error: 'pgrp' was not declared in this scope
   49 |     svgw.writePackGroup(pgrp);`

So I failed to run the script. Any help or hint would be appreciated.

**Comment by MCemGunes** [comment]
I figured out the solution:

I was trying to run the script in the wrong directory. When I run the commands as shown below I get the result. It is tested on Ubuntu 22.04, the docker environment that I posted. 

create build directory and in build directory run:

```
cmake .. -DLIBNEST2D_HEADER_ONLY=OFF  -DRP_ENABLE_DOWNLOADING=ON -DCMAKE_INSTALL_PREFIX=/app/libnest/

cmake --build . --target install
```
 
Next, Go to examples folder and run the following commands,

```
cmake .  

make 
```
to run the example just type `./example`. You will see the results as .svg files in the folder. 

I hope it will help starters or people with limited experience in C++.

**Comment by enouxdn** [comment]
When i run cmake .. -DLIBNEST2D_HEADER_ONLY=OFF  -DRP_ENABLE_DOWNLOADING=ON -DCMAKE_INSTALL_PREFIX=
Why it failed?

CMake Error at cmake_modules/RequirePackage.cmake:218 (message):
  Build step (Release) for NLopt failed:
Call Stack (most recent call first):
  cmake_modules/RequirePackage.cmake:252 (download_package)
  include/libnest2d/optimizers/nlopt/CMakeLists.txt:3 (require_package)


-- Configuring incomplete, errors occurred!
