### ISSUE TITLE
Nest example coding questions

### ISSUE THREAD

**Issue by samsonsite1** [tamasmeszaros/libnest2d#6]
Hello,
I'm new to libnest2d and I have a couple of questions.

- How can I configure the call to nest() to include a certain amount of spacing around my shapes?
- Is it possible to configure nest() to not rotate my shapes?  Just translation, no rotation?

I'm looking at this example:

    // Perform the nesting with a box shaped bin
    auto result = nest(input, Box(150000000, 150000000));

Another question, how can I tell if all shapes were nested successfully without overflowing?  
How do I pick the optimal bounding box size that will fit them all?

How can I build up a shape item by adding vertex points to it, one at a time?
Item item;	// how to add points to this class, one at a time?

Thanks.

**Comment by tamasmeszaros** [comment]
Hello
* The nest function has a parameter "min distance" which will ensure the spacing.
* Yes, but you have to set it in the placer configuration. If you use the nfp placer, there is a parameter for that. Look at the top of nfpplacer.hpp, there are the available config values.
* You can tell from the return value which is a vector of item vectors corresponding to each logical bin that was filled. If you want to find your original items, you have to complicate your life and the nest function only will not be enough. (Im working on this, just have to merge it to master)
* The optimal bin search: You could just give it a huge bin, let it do the nesting and from the result which should contain only one logical bin, create a bounding box around the nested pile of polygons and there you have it.
* Item class is not designed for polygon construction. That has to be done on the raw polygon it contains. You can get it with rawShape() method or the transformedShape() method of Item objects. Modify that and create a new Item object to do the nesting.

**Comment by subhashreehari** [comment]
@tamasmeszaros 
 Even I have similar kind of doubts on this 

1. Is it possible to get the optimum "no. of shapes" that can be placed from the Bin size?

2. How can I place the shapes on the bin horizontally/vertically without optimization?
Like the image below
![sample1](https://user-images.githubusercontent.com/44163781/64953300-1e865d80-d8a0-11e9-816c-df034b2b5851.png)
Thanks!

**Comment by samsonsite1** [comment]
@tamasmeszaros

Hello,
Thanks for the reply.

Yes, I need to track the items that I nest, this is most important.  I was assuming the order that I insert them was the same order as they come out in the result.  Is it possible to tag them with an unique id?

**Comment by tamasmeszaros** [comment]
Yes it is. I have made it much more easier but I need some time to polish and publish the changes. I will come back to this issue soon, (few weeks). If you need this immediately, look at the Nester classes interface

**Comment by tamasmeszaros** [comment]
As to placing items in a grid: there is two things you can do: forget about libnest and do it manually. libnest is really about the optimization part. However, I think you can get almost any arrangement you want be using a custom optimization kernel. Which might be a hard thing to develop is you have strict aesthetic or alignment requirements.

**Comment by tamasmeszaros** [comment]
Hello,
so the new interface is in master now. The nest function no longer returns this weird PackGroup structure but it takes non-const iterators to Item collections. It arranges them but the order of items in the input collection remains the same, only the transformations and the binId() changes. Se the examples and tests for more info.

**Comment by samsonsite1** [comment]
Thanks for the update!

I'm trying to compile the example code on the front page, and after fixing a small typo:

    for(Item& r : input) {
        //auto polygon = item.transformedShape();
        auto polygon = r.transformedShape();
        // render polygon...
    }

It's crashing when nest() is called.

Debugger returned:
Unhandled exception at 0x774FC5AF in test.exe: Microsoft C++ exception: 
libnest2d::GeometryException at memory location 0x003DD6F0.

The debugger stopped on this line:
if(!valid) throw GeometryException(GeomErr::MERGE);

from:
include\libnest2d\backends\clipper\geometries.hpp

function:
merge(const std::vector<PolygonImpl>& shapes)

Using:
Visual Studio 2015
cmake 3.15.2
ClipperLib 6.4.2
NLopt 2.6.1
Boost 1.65.1

I added these two pre-processor defintions:
LIBNEST2D_GEOMETRIES_clipper
LIBNEST2D_OPTIMIZER_nlopt

I'm using the same libraries as before, so I'm not sure why it's crashing.

**Comment by samsonsite1** [comment]
I also compiled the provided example code that uses SVGWriter.
The code doesn't fully execute or write out a SVG file.

It prints out a message:
parts left: 26

then exits.  I believe it crashes in the same spot as above (GeometryException).

**Comment by samsonsite1** [comment]
I also had some minor issues getting the project built using cmake. It seems some changes were made from last time.

I usually run the cmake-gui and and fill in any missing entries by hand, like CLIPPER_LIBRARIES.  But, whenever I did this, cmake would automatically delete my entries, which was unusual.  I had to comment out several "unset" lines for cmake to keep my entries.
