### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tarnh** [tamasmeszaros/libnest2d#8]
Hi Tamas,

after building with
 `cmake . -DLIBNEST2D_HEADER_ONLY=OFF -DCMAKE_INSTALL_PREFIX=/usr`
I've installed with `cmake --build . --target install`

Weirdly the files are getting installed to `/libnest2d/usr/lib/libnest2d_clipper_nlopt.a`
What do you you recommend for standard (LSB) installation paths?

System: ArchLinux + current gcc

**Comment by tamasmeszaros** [comment]
Hi @tarnh!
Could you try with the latest master?

**Comment by tarnh** [comment]
I have tried with latest master!

**Comment by tamasmeszaros** [comment]
Is this issue still occurring? If so could you please try it with recent master (as of now) and let me know the result?

**Comment by tarnh** [comment]
No, not yet working. But if I should use other commands for installation, please tell me so.

**Comment by tamasmeszaros** [comment]
The commands should be fine and the standard prefix dir is determined by CMake if you don't specify `CMAKE_INSTALL_PREFIX`. If you haven't deleted your cmake cache, do it and try again. For me the installation works properly in the Ubuntu build server.

**Comment by tarnh** [comment]
Thanks, working now!
